- src/app/pages/index/posts-preview/posts-preview.component.html
- src/app/pages/index/posts-preview/posts-preview.component.scss
> [KL-209] update styles for component

- src/app/product-list/product-list.component.html
- src/app/product-list/product-list.component.ts
> [KL-190] fix pagination

- src/app/header/header.component.scss
- src/app/header/search-bar/search-bar.component.scss
- src/app/product-list/product-list.component.scss
- src/app/product-list/product-list.component.ts
> [KL-246] fix bugs

- src/app/button-up/button-up.component.ts
> [KL-246] fix scroll bug in chrome

- src/app/header/header.component.scss
- src/app/pages/index/index.component.html
- src/app/pages/index/index.component.scss
- src/app/pages/index/index.module.ts
- src/app/pages/product/product.service.ts
- src/app/products-preview/products-preview.component.html
- src/app/products-preview/products-preview.component.ts
- src/app/recently-added-products/recently-added-products.component.html
- src/app/recently-added-products/recently-added-products.component.spec.ts
- src/app/recently-added-products/recently-added-products.component.ts
- src/app/recently-added-products/recently-added-products.module.ts
> [KL-210] add recently added products preview on index page

- src/app/header/search-bar/search-bar.component.html
- src/app/header/search-bar/search-bar.component.scss
- src/app/header/search-bar/search-bar.component.ts
- src/app/products-preview/products-preview.component.ts
> Kl 272 search with keys

- src/app/pages/product/product.component.html
- src/app/pages/product/product.component.scss
- src/app/pages/product/product.component.ts
- src/app/products-preview/products-preview.component.scss
> Kl 273 instructions popup for quick review

- src/app/pages/product/product-details/product-details.component.scss
> [KL-312] change styles for chars

- src/app/header/header.component.scss
- src/app/linked-categories/linked-categories.component.scss
> [KL-316] change styles for side bar on index page

- src/app/linked-categories/linked-categories.component.scss
- src/app/product-list/filter/filter.component.scss
> Kl 316 categories navigation

- src/app/linked-categories/linked-categories.component.scss
- src/app/linked-categories/linked-categories.component.ts
> [KL-316] change categories styles

- src/app/pages/product/product.component.scss
> [KL-273] change btn styles

- src/app/pages/product/product.component.html
- src/app/pages/product/product.component.scss
> [KL-336] change product categories styles

- src/app/pages/category/category.component.scss
- src/app/product-list-item/product-list-item.component.scss
- src/app/product-list/product-list.component.scss
- src/app/product-list/range-slider/range-slider.component.scss
- src/app/products-preview/products-preview.component.scss
- src/assets/styles/abstracts/_variables.scss
- src/assets/styles/components/_button.scss
> [KL-340] change btn styles

- src/app/product-list-item/product-list-item.component.scss
- src/app/products-preview/products-preview.component.scss
> [KL-340] change btn styles for mobile

- src/app/address-form/address-form.component.ts
- src/app/pages/checkout/order-customer-info/order-customer-info.component.html
- src/app/pages/checkout/order-customer-info/order-customer-info.component.ts
> Kl 305 user info pre fill

- src/app/address-form/address-form.component.scss
- src/app/cart/cart.component.html
- src/app/cart/cart.component.scss
- src/app/pages/checkout/checkout.component.scss
- src/app/shared/quantity-control/quantity-control.component.scss
> [KL-348] change cart styles

- src/app/cart/cart.component.scss
> [KL-348] refactor code

- src/app/cart/cart.component.scss
> [KL-348] fix img height bug

- src/app/breadcrumbs/breadcrumbs.component.scss
- src/app/header/header.component.scss
- src/app/pages/product/product-gallery/product-gallery.component.scss
- src/app/pages/product/product.component.scss
> Kl 355 logo styles on mobile

- src/app/header/header.component.ts
- src/app/pages/product/product.component.html
- src/app/pages/product/product.component.scss
- src/app/pages/product/product.component.ts
- src/app/pages/store-reviews/store-reviews.component.html
- src/app/pages/store-reviews/store-reviews.component.scss
- src/app/pages/store-reviews/store-reviews.component.ts
- src/app/pages/store-reviews/store-reviews.module.ts
- src/app/product-list/product-list.component.html
- src/app/product-list/product-list.component.ts
- src/app/product-list/product-list.module.ts
- src/app/product-list/sorting/sorting.component.html
- src/app/product-list/sorting/sorting.component.ts
- src/app/rating-stars/rating-stars.component.html
- src/app/rating-stars/rating-stars.component.scss
- src/app/rating-stars/rating-stars.component.ts
- src/app/review/review.component.scss
- src/app/service-menu/service-menu.component.html
- src/app/services/store-review/store-review.service.ts
- src/app/shared/enums/sort.enum.ts
> Kl 354 catchy summary sorting

- src/app/pages/product/product.component.scss
> [KL-354] fix styles on product page

- src/app/pages/store-reviews/store-reviews.component.ts
> [KL-369] add on review from email notification

- src/app/select-autocomplete/select-autocomplete.component.ts
> KL-282 add default cities

- src/app/product-list/product-list.component.scss
Заметил на сайте, что прыгает панель фильтров, увеличил минимальную высоту на 2 пикселя
> changed min-height fixed-bar

- src/app/cart/cart.component.scss
- src/assets/styles/components/_modal.scss
> KL-415-fix-cart-bugs

- src/app/pages/account/account.module.ts
- src/app/pages/account/customer-info/account-customer-info.component.html
- src/app/pages/account/customer-info/account-customer-info.component.ts
> KL-409 add phone number field

- src/app/announcement/announcement.component.html
- src/app/announcement/announcement.component.scss
- src/app/announcement/announcement.component.spec.ts
- src/app/announcement/announcement.component.ts
- src/app/announcement/announcement.module.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/app/services/announcement/announcement.service.spec.ts
- src/app/services/announcement/announcement.service.ts
- src/app/shared/dtos/announcement.dto.ts
> [KL-411] add announcement

- src/app/announcement/announcement.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.ts
- src/app/header/search-bar/search-bar.component.html
- src/app/header/search-bar/search-bar.component.ts
> [KL-411] fix search bar z-index

- src/app/announcement/announcement.component.scss
- src/app/header/header.component.scss
- src/app/header/search-bar/search-bar.component.html
- src/app/header/sidebar-menu/sidebar-menu.component.scss
- src/assets/styles/abstracts/_variables.scss
- src/assets/styles/components/_modal.scss
> [KL-411] fix media modal z-index

- src/app/announcement/announcement.component.html
- src/app/announcement/announcement.component.scss
- src/app/announcement/announcement.component.ts
- src/app/shared/dtos/announcement.dto.ts
> Kl 441 announcement

- src/app/pages/checkout/checkout-block.scss
- src/app/pages/checkout/payment-methods/payment-methods.component.html
> [KL-449] fix order methods styles

- src/app/pages/checkout/checkout.component.ts
- src/app/services/customer/customer.service.ts
> [KL-344] add vibration api

- src/app/pages/checkout/checkout.component.ts
- src/app/services/customer/customer.service.ts
- src/app/shared/helpers/vibrate.function.ts
> Kl 344 vibration api

- src/app/announcement/announcement.component.ts
> fix announcement

- src/app/add-review/add-review.component.html
- src/app/add-review/add-review.component.scss
- src/app/add-review/add-review.component.ts
- src/app/pages/product/product-details/product-details.component.html
- src/app/pages/product/product-details/product-details.component.ts
- src/app/pages/store-reviews/store-reviews.component.html
- src/app/pages/store-reviews/store-reviews.component.scss
- src/app/pages/store-reviews/store-reviews.component.ts
> KL-450 refactor add review modal

- src/app/add-review/add-review.component.html
- src/app/add-review/add-review.component.scss
- src/app/add-review/add-review.component.ts
- src/app/pages/store-reviews/store-reviews.component.html
- src/app/pages/store-reviews/store-reviews.component.ts
> KL-450 add input placeholder

- src/app/blog-posts-list/blog-posts-list.component.html
- src/app/select-autocomplete/select-autocomplete.component.scss
> KL-475 fix translation/fix dropdown top style

- package-lock.json
- package.json
- src/app/app.module.ts
- src/main.ts
> Kl 456 error monitoring service

- src/app/pages/product/product.component.html
- src/app/pages/product/product.component.scss
- src/app/pages/product/product.component.ts
- src/app/product-list-item/product-list-item.component.html
- src/app/product-list-item/product-list-item.component.scss
- src/app/product-list-item/product-list-item.component.ts
- src/app/shared/dtos/product-list-item.dto.ts
- src/app/shared/dtos/product.dto.ts
- src/app/shared/enums/product-label-type.enum.ts
- src/assets/styles/abstracts/_variables.scss
> Kl 455 product labels

- src/app/select-autocomplete/select-autocomplete.component.scss
> KL-421 fix empty row in dropdown

- src/app/cart/cart.component.html
- src/app/cart/cart.component.scss
> fix styles buy btn

- src/app/cart/cart.component.scss
> change buy btn hover styles

- src/app/cart/cart.component.scss
> fix buy btn arrow

- src/app/select-autocomplete/select-autocomplete.component.scss
> change placeholder font-size

- src/app/select-autocomplete/select-autocomplete.component.scss
> fix option padding

- src/app/banner/banner.component.html
- src/app/banner/banner.component.scss
- src/app/banner/banner.component.ts
> [KL-416] add swiper/automatic slider

- src/app/banner/banner.component.ts
> [KL-416] fix server rendering

- src/app/pages/product/product.component.scss
> set product buy info higher in product info section

- src/app/pages/category/category.component.scss
> Subcategories styles

- package-lock.json
- package.json
- src/app/banner/banner.component.html
- src/app/banner/banner.component.scss
- src/app/banner/banner.component.ts
> Kl 416 banner

- src/app/address-form/address-form.component.html
- src/app/address-form/address-form.component.scss
- src/app/shared/directives/input-capitalize.directive.spec.ts
- src/app/shared/directives/input-capitalize.directive.ts
- src/app/shared/shared.module.ts
> [KL-498] capitalize name

- src/app/add-review/add-review.component.html
- src/app/add-review/add-review.component.ts
- src/app/add-review/add-review.module.ts
- src/app/pages/product/product-details/product-details.component.html
- src/app/pages/product/product-details/product-details.component.ts
- src/app/pages/store-reviews/store-reviews.component.html
- src/app/pages/store-reviews/store-reviews.component.ts
> [KL-504] add preloader

- src/app/banner/banner.component.html
- src/app/banner/banner.component.scss
- src/app/banner/banner.component.ts
> [KL-416] add fifth element / modify slider

- src/app/add-review/add-review.component.scss
- src/app/banner/banner.component.scss
- src/app/header/header.component.scss
- src/app/pages/category/category.component.scss
- src/app/pages/index/index.component.html
- src/app/pages/index/index.component.scss
- src/app/pages/index/index.component.ts
> Kl 528 index page nav styles

- src/app/header/header.component.scss
- src/app/header/search-bar/search-bar.component.scss
- src/app/linked-categories/linked-categories.component.scss
- src/app/pages/category/category.component.scss
> Kl 536 desktop page full width
